adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.AdminUserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.AdminUserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.AdminUserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.AdminUserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryView.as_view(), name='products_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/', adminapp.AdminOrderList.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.AdminOrderUpdate.as_view(), name='orders_update'),
    path('orders/delete/<int:pk>/', adminapp.AdminOrderDelete.as_view(), name='orders_delete'),
    path('orders/read/<int:pk>/', adminapp.AdminOrderRead.as_view(), name='orders_read'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name="index"),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('products/<int:pk>/', mainapp.product_page, name='product_page'),
]

adminapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.db import transaction


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    def __str__(self):
        return self.name

    @transaction.atomic()
    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)
        # self.category.delete()


class ProductQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.delete()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='category')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    objects = ProductQuerySet.as_manager()

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.select_related('category').\
            filter(is_active=True, category__is_active=True).\
            order_by('category', 'name')

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)

adminapp/forms.py
from django.contrib.auth import get_user_model
from django import forms

from authapp.forms import ShopUserEditForm, HiddenInput
from mainapp.models import ProductCategory, Product
from ordersapp.models import Order


class AdminShopUserUpdateForm(ShopUserEditForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password',
                  'email', 'age', 'avatar',
                  'is_staff', 'is_superuser', 'is_active')


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0,
                                  max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        exclude = ()


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class AdminOrdersEditForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

adminapp/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.models import F

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import AdminShopUserUpdateForm, ProductEditForm, \
    ProductCategoryEditForm, AdminOrdersEditForm
from ordersapp.models import Order
from mixins.mixins import SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin


class AdminUserListView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ShopUser
    page_title = 'админка/пользователи'


class AdminUserCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/создание'


class AdminUserUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ShopUser
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/редактирование'


class AdminUserDeleteView(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/удаление'


class CategoryCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/создание'


class CategoryUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/редактирование'

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.category.update(
                    price=F('price') * (1 - discount / 100)
                )
        return super().form_valid(form)


class CategoryView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ProductCategory
    page_title = 'админка/категории'


class CategoryDeleteView(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/удаление'


class ProductCreateView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        CreateView):
    model = Product
    form_class = ProductEditForm
    page_title = 'админка/продукты/создание'

    def get_initial(self):
        return {'category': get_object_or_404(ProductCategory,
                                              pk=self.kwargs['pk'])}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_id'] = self.kwargs['pk']
        return context


class ProductsCategoryView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = Product
    page_title = 'админка/продукты категории'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(ProductCategory,
                                                pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs['pk']).order_by(
            'name')


class ProductDetailView(SuperUserOnlyMixin, PageTitleMixin, DetailView):
    model = Product
    page_title = 'админка/продукт'


class ProductUpdateView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        UpdateView):
    model = Product
    form_class = ProductEditForm
    page_title = 'админка/продукты/редактирование'


class ProductDeleteView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        DeleteView):
    model = Product
    page_title = 'админка/продукты/удаление'


class AdminOrderList(PageTitleMixin, ListView):
    model = Order
    page_title = 'админка/заказы'
    template_name = 'ordersapp/orders_list.html'


class AdminOrderUpdate(UpdateView):
    model = Order
    form_class = AdminOrdersEditForm
    success_url = reverse_lazy('admin:orders')
    template_name = 'ordersapp/orders_form.html'
    page_title = 'админка/заказы/редактирование'


class AdminOrderDelete(PageTitleMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('admin:orders')
    template_name = 'ordersapp/orders_confirm_delete.html'
    page_title = 'админка/заказы/удаление'

    def delete(self, request, *args, **kwargs):
        super().delete(request, *args, **kwargs)
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)


class AdminOrderRead(DetailView):
    model = Order
    template_name = 'ordersapp/orders_detail.html'
    page_title = 'админка/заказы/просмотр'


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.category.update(is_active=True)
        else:
            instance.category.update(is_active=False)

mainapp/views.py
from random import sample
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache

from geekshop.settings import LOW_CACHE
from mainapp.models import ProductCategory, Product


def get_links_menu():
    if LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        product = cache.get(key)
        if product is None:
            product = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, product)
        return product
    return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_hot_product():
    product = get_products()
    return sample(list(product), 1)[0]


def get_same_products(hot_product):
    same_product = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_product


def main(request):
    products_list = Product.get_items()
    context = {
        'page_title': 'главная',
        'products_list': products_list
    }
    return render(request, "mainapp/index.html", context)


def products(request, pk=None, page=1):
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все',
            }
            products_list = get_products()
        else:
            category = get_category(pk)
            products_list = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                order_by('price')

        paginator = Paginator(products_list, 2)
        try:
            product_paginator = paginator.page(page)
        except PageNotAnInteger:
            product_paginator = paginator.page(1)
        except EmptyPage:
            product_paginator = paginator.page(paginator.num_pages)

        context = {
                'page_title': 'товары категории',
                'links_menu': get_links_menu(),
                'category': category,
                'products_list': product_paginator,
            }
        return render(request, "mainapp/category_products.html", context)

    hot_product = get_hot_product()
    context = {
        'page_title': 'продукты',
        'links_menu': get_links_menu(),
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, "mainapp/products.html", context)


def contact(request):
    context = {'page_title': 'контакты'}
    return render(request, "mainapp/contact.html", context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'старница продукта',
        'product': product,
        # 'categories': get_category(product.category.pk),
    }
    return render(request, 'mainapp/product_page.html', context)

adminapp/templates/mainapp/product_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        Уверены что хотите удалить продукт "{{ object.name|capfirst }}"?
        <form action="{% url 'admin:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/mainapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт <strong>{{ object.category.name|capfirst }} {{ object.name|capfirst }}</strong>
        </div>
        <img src="/media/{{ object.image }}" alt="{{object.name}} ">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href="{% url 'admin:product_update' object.pk %}">
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:product_delete' object.pk %}">
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:products_category' object.category.pk %}">
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

adminapp/templates/mainapp/product_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            {% if category_id %}
                <a href="{% url 'admin:products_category'  category_id %}">
                  к списку продуктов
                </a>
            {% else %}
                <a href="{% url 'admin:products_category'  object.category_id %}">
                  к списку продуктов
                </a>
            {% endif %}
        </button>
    </div>
{% endblock %}

adminapp/templates/mainapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href="{% url 'admin:product_create' category.pk %}">
                новый продукт
            </a>
        </button>

        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|capfirst }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href="{% url 'admin:product_read' object.pk %}">
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:product_update' object.pk %}">
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:product_delete' object.pk %}">
                            удалить
                        </a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price}} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|capfirst }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/mainapp/productcategory_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %]

{% block content %}
    <div class="category_delete">
        Уверены что хотите удалить категорию "{{ object.name|capfirst }}"?
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/mainapp/productcategory_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:categories' %}">
              к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/mainapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href="{% url 'admin:category_create' %}">
                новая категория
            </a>
        </button>

        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|capfirst }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href="{% url 'admin:products_category' object.pk %}">
                            товары категории
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:category_update' object.pk %}">
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:category_delete' object.pk %}">
                            удалить
                        </a>
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|capfirst }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}