authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:product_pk>', basketapp.add, name='add'),
    path('remove/<int:pk>', basketapp.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),
]

geekshop/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name="index"),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('products/<int:pk>/', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models
from django.db import transaction


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    def __str__(self):
        return self.name

    @transaction.atomic()
    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)
        # self.category.delete()


class ProductQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.delete()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='category')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    objects = ProductQuerySet.as_manager()

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.select_related('category').\
            filter(is_active=True, category__is_active=True).\
            order_by('category', 'name')

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)

mainapp/views.py
from random import sample
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache

from geekshop.settings import LOW_CACHE
from mainapp.models import ProductCategory, Product


def get_links_menu():
    if LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        product = cache.get(key)
        if product is None:
            product = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, product)
        return product
    return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_hot_product():
    product = get_products()
    return sample(list(product), 1)[0]


def get_same_products(hot_product):
    same_product = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_product


def main(request):
    products_list = Product.get_items()
    context = {
        'page_title': 'главная',
        'products_list': products_list
    }
    return render(request, "mainapp/index.html", context)


def products(request, pk=None, page=1):
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все',
            }
            products_list = get_products()
        else:
            category = get_category(pk)
            products_list = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                order_by('price')

        paginator = Paginator(products_list, 2)
        try:
            product_paginator = paginator.page(page)
        except PageNotAnInteger:
            product_paginator = paginator.page(1)
        except EmptyPage:
            product_paginator = paginator.page(paginator.num_pages)

        context = {
                'page_title': 'товары категории',
                'links_menu': get_links_menu(),
                'category': category,
                'products_list': product_paginator,
            }
        return render(request, "mainapp/category_products.html", context)

    hot_product = get_hot_product()
    context = {
        'page_title': 'продукты',
        'links_menu': get_links_menu(),
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, "mainapp/products.html", context)


def contact(request):
    context = {'page_title': 'контакты'}
    return render(request, "mainapp/contact.html", context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'старница продукта',
        'product': product,
        # 'categories': get_category(product.category.pk),
    }
    return render(request, 'mainapp/product_page.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {{page_title|default:"магазин"|capfirst}}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
        {% block menu %}
           {% include 'includes/inc_menu.html' %}
        {% endblock %}

        {% block content %}

        {% endblock %}
    </div>

    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>

                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>

                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>

            <p class="small">&copy; GB 2017</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/category_products.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
	{{block.super}}
</div>

<div class="details">
	<div class="links clearfix">
		{% include 'includes/inc_categories_menu.html' %}
	</div>
{% endblock %}

{% block content %}
	<div class="products_list">
		<div class="title clearfix">
			<h2>Продукты категории {{ category.name|upper }} </h2>
			<div class="paginator">
				{% if products_list.has_previous %}
					<a href="{% url 'main:page' category.pk products_list.previous_page_number %}">
						<
					</a>
				{% endif %}
				<span class="current">
					страница {{ products_list.number }} из {{ products_list.paginator.num_pages }}
				</span>
				{% if products_list.has_next %}
					<a href="{% url 'main:page' category.pk products_list.next_page_number %}">
						>
					</a>
				{% endif %}
			</div>
		</div>
		<div class="related-products clearfix">

		{% for prod in products_list %}
			<div class="block">
				<a href="{% url 'main:product_page' prod.pk %}"><img src="/media/{{ prod.image }}" alt="img">
					<div class="text">
						<img src="{% static 'img/icon-hover.png' %}" alt="img">
						<h4>{{ prod.short_desc }}</h4>
						<p>{{ prod.description }} </p>
					</div>
				</a>
			</div>
			{% endfor %}

		</div>

	</div>
</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}

<body>
	<div class="container">
		{% block menu %}
		<div class="hero">
			{{block.super}}
			<h1>наши контакты</h1>
		</div>
		{% endblock %}

		{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
		{% endblock %}
	</div>
			
</body>

mainapp/templates/mainapp/index.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}

<body>
	<div class="container">
		{% block menu %}
		<div class="slider">
			{{block.super}}

			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for prod in products_list|slice:":3" %}
					<div class="block">
							<a href="#"><img src="/media/{{ prod.image }}" alt="img">
								<div class="text">
									<img src="{% static 'img/icon-hover.png' %}" alt="img">
									<h4>{{ prod.short_desc }}</h4>
									<p>{{ prod.description }} </p>
								</div>
							</a>
					</div>
				{% endfor %}
			</div>
		</div>
		
		<div class="clr"></div>
		{% endblock %}
	</div>
	
</body>

mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
	{{ block.super }}
</div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name|capfirst }}</h3>
                <br>
                <p class="price">{{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    в корзину <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
<div class="hero-white">
	{{block.super}}
</div>

<div class="details">
	<div class="links clearfix">
		{% include 'includes/inc_categories_menu.html' %}
	</div>
{% endblock %}

{% block content %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="/media/{{ hot_product.image }}">
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ hot_product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' hot_product.pk %}"
				class="red-button">
					заказать
				<i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ hot_product.description }}
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">

		{% for prod in same_products %}
			<div class="block">
					<a href="#"><img src="/media/{{ prod.image }}" alt="img">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>{{ prod.short_desc }}</h4>
							<p>{{ prod.description }} </p>
						</div>
					</a>
			</div>
			{% endfor %}

		</div>

	</div>
</div>

<div class="clr"></div>
{% endblock %}