adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.AdminUserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.AdminUserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.AdminUserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.AdminUserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryView.as_view(), name='products_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/', adminapp.AdminOrderList.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.AdminOrderUpdate.as_view(), name='orders_update'),
    path('orders/delete/<int:pk>/', adminapp.AdminOrderDelete.as_view(), name='orders_delete'),
    path('orders/read/<int:pk>/', adminapp.AdminOrderRead.as_view(), name='orders_read'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='index'),
    path('create/', ordersapp.OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='delete'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='read'),
    path('complate/<int:pk>/', ordersapp.forming_complete, name='complete'),
    path('update/ajax/<int:pk>/', ordersapp.ajax_update, name='ajax_update'),
]

adminapp/models.py
from django.db import models

# Create your models here.

ordersapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.functional import cached_property
from django.db.models import F

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='users_order')
    created_data = models.DateTimeField(verbose_name='время добавления', db_index=True, auto_now_add=True)
    update_data = models.DateTimeField(verbose_name='время обновления', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', db_index=True, default=True)

    class Meta:
        ordering = ('-created_data',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    @cached_property
    def is_forming(self):
        return self.status == self.FORMING

    @cached_property
    def get_summary(self):
        items = self.order.select_related()
        summary = {
            'total_quantity': sum(map(lambda x: x.quantity, items)),
            'total_cost': sum(map(lambda x: x.product_cost, items))
        }
        return summary

    def delete(self, using=None, keep_parents=False):
        self.order.delete()
        self.status = Order.CANCEL
        self.save()


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.delete()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE, related_name='product')
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    objects = OrderItemQuerySet.as_manager()

    @cached_property
    def product_cost(self):
        return self.product.price * self.quantity

    def delete(self, using=None, keep_parents=False):
        self.product.quantity += self.quantity
        self.product.save()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.pk:
            old_value = Order.objects.get(pk=self.order.pk).order.get(pk=self.pk).quantity
            self.product.quantity += old_value - self.quantity
        else:
            self.product.quantity -= self.quantity

        self.product.save()
        super().save()

adminapp/forms.py
from django.contrib.auth import get_user_model
from django import forms

from authapp.forms import ShopUserEditForm, HiddenInput
from mainapp.models import ProductCategory, Product
from ordersapp.models import Order


class AdminShopUserUpdateForm(ShopUserEditForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password',
                  'email', 'age', 'avatar',
                  'is_staff', 'is_superuser', 'is_active')


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0,
                                  max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        exclude = ()


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class AdminOrdersEditForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

adminapp/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.models import F

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import AdminShopUserUpdateForm, ProductEditForm, \
    ProductCategoryEditForm, AdminOrdersEditForm
from ordersapp.models import Order
from mixins.mixins import SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin


class AdminUserListView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ShopUser
    page_title = 'админка/пользователи'


class AdminUserCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/создание'


class AdminUserUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ShopUser
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/редактирование'


class AdminUserDeleteView(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin:users')
    page_title = 'админка/пользователи/удаление'


class CategoryCreateView(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/создание'


class CategoryUpdateView(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/редактирование'

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.category.update(
                    price=F('price') * (1 - discount / 100)
                )
        return super().form_valid(form)


class CategoryView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ProductCategory
    page_title = 'админка/категории'


class CategoryDeleteView(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin:categories')
    page_title = 'админка/категории/удаление'


class ProductCreateView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        CreateView):
    model = Product
    form_class = ProductEditForm
    page_title = 'админка/продукты/создание'

    def get_initial(self):
        return {'category': get_object_or_404(ProductCategory,
                                              pk=self.kwargs['pk'])}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_id'] = self.kwargs['pk']
        return context


class ProductsCategoryView(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = Product
    page_title = 'админка/продукты категории'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(ProductCategory,
                                                pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs['pk']).order_by(
            'name')


class ProductDetailView(SuperUserOnlyMixin, PageTitleMixin, DetailView):
    model = Product
    page_title = 'админка/продукт'


class ProductUpdateView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        UpdateView):
    model = Product
    form_class = ProductEditForm
    page_title = 'админка/продукты/редактирование'


class ProductDeleteView(SuperUserOnlyMixin, PageTitleMixin, GetSuccessUrlMixin,
                        DeleteView):
    model = Product
    page_title = 'админка/продукты/удаление'


class AdminOrderList(PageTitleMixin, ListView):
    model = Order
    page_title = 'админка/заказы'
    template_name = 'ordersapp/orders_list.html'


class AdminOrderUpdate(UpdateView):
    model = Order
    form_class = AdminOrdersEditForm
    success_url = reverse_lazy('admin:orders')
    template_name = 'ordersapp/orders_form.html'
    page_title = 'админка/заказы/редактирование'


class AdminOrderDelete(PageTitleMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('admin:orders')
    template_name = 'ordersapp/orders_confirm_delete.html'
    page_title = 'админка/заказы/удаление'

    def delete(self, request, *args, **kwargs):
        super().delete(request, *args, **kwargs)
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.success_url)


class AdminOrderRead(DetailView):
    model = Order
    template_name = 'ordersapp/orders_detail.html'
    page_title = 'админка/заказы/просмотр'


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.category.update(is_active=True)
        else:
            instance.category.update(is_active=False)

ordersapp/views.py
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.db import transaction
from django.shortcuts import get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.http import JsonResponse

from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderForm, OrderItemForm
from mainapp.models import Product
from mixins.mixins import PageTitleMixin, UserOnlyMixin


class OrderList(UserOnlyMixin, ListView, PageTitleMixin):
    model = Order
    page_title = 'заказы'

    def get_queryset(self):
        return self.request.user.users_order.all()


class OrderCreate(UserOnlyMixin, CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'заказы/создание'
        OrderFromSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=3)

        if self.request.POST:
            formset = OrderFromSet(self.request.POST, self.request.FILES)
        else:
            context['form'].initial['user'] = self.request.user
            basket_item = self.request.user.basket.all()
            if basket_item and basket_item.count():
                OrderFromSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm,
                                                     extra=basket_item.count() + 1)

                formset = OrderFromSet()
                for form, item in zip(formset.forms, basket_item):
                    form.initial['product'] = item.product
                    form.initial['quantity'] = item.quantity
                    form.initial['price'] = item.product.price
            else:
                formset = OrderFromSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            order = super().form_valid(form)
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
                self.request.user.basket.all().delete()

        if self.object.total_quantity == 0:
            self.object.delete()

        return order


class OrderUpdate(UserOnlyMixin, UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'зазазы/редактирование'
        OrderFromSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFromSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            queryset = self.object.order.select_related('product')
            formset = OrderFromSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                instance = form.instance
                if instance.pk:
                    form.initial['price'] = instance.product.price
                    form.initial['total_price'] = instance.product.price * instance.quantity
                    form.initial['total_quantity'] = instance.product.quantity
        context['orderitems'] = formset
        return context

    @transaction.atomic()
    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        if orderitems.is_valid():
            orderitems.save()
        if self.object.get_summary['total_cost'] == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderDelete(UserOnlyMixin, DeleteView, PageTitleMixin):
    model = Order
    success_url = reverse_lazy('orders:index')
    page_title = 'заказы/удаление'


class OrderRead(UserOnlyMixin, DetailView, PageTitleMixin):
    model = Order
    page_title = 'заказы/просмотр'


def forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('orders:index'))


def ajax_update(request, pk=None):
    if request.is_ajax:
        product = Product.objects.get(pk=int(pk))
        return JsonResponse({'price': product and product.price or 0,
                             'quantity': product and product.quantity or 0})

adminapp/templates/ordersapp/orders_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить заказ?</div>
        {% include 'ordersapp/includes/inc_admin_order_summary.html' %}
        <form action="{% url 'admin:orders_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:orders' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/ordersapp/orders_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    {% include 'ordersapp/includes/inc_admin_order_summary.html' %}
    <div class="basket_container">
        <div class="basket_list">
            {% for item in object.order.select_related %}
                <div class="basket_record">
                    <img src="{{ item.product.image|media_folder_products }}" alt="{{ item.product.short_desc }}">
                    <span class="category_name">{{ item.product.category.name }}</span>
                    <span class="product_name">{{ item.product.name }}</span>
                    <span class="product_price">{{ item.product.price }}&nbspруб</span>
                    <span class="product_quantity"> x {{ item.quantity }} шт</span>
                    <span class="product_cost"> = {{ item.get_product_cost }}&nbspруб</span>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'ordersapp/includes/inc_admin_order_actions.html' %}
{% endblock %}

adminapp/templates/ordersapp/orders_form.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    {% include 'ordersapp/includes/inc_admin_order_summary.html' %}
    <div class="order_form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="basket_container">
                <div class="basket_list">
                    {% for item in object.order.select_related %}
                        <div class="basket_record">
                            <img src="{{ item.product.image|media_folder_products }}" alt="{{ item.product.short_desc }}">
                            <span class="category_name">{{ item.product.category.name }}</span>
                            <span class="product_name">{{ item.product.name }}</span>
                            <span class="product_price">{{ item.product.price }}&nbspруб</span>
                            <span class="product_quantity"> x {{ item.quantity }} шт</span>
                            <span class="product_cost"> = {{ item.get_product_cost }}&nbspруб</span>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <input type="submit" value="сохранить" class="btn btn-default btn-round form-control last">
        </form>
    </div>
    {% include 'ordersapp/includes/inc_admin_order_actions.html' %}
{% endblock %}

adminapp/templates/ordersapp/orders_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    {% if not object_list %}
        <div class="h2 text-center head">
            Заказов пока нет
        </div>
    {% else %}
        <table class="table order_list">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Пользователь</th>
                    <th>Создан</th>
                    <th>Обновлен</th>
                    <th>Статус</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr bgcolor="{% if not item.is_active %}#dc143c{% endif %}"  >
                        <td class="td1 order_list">{{ item.pk }}</td>
                        <td>{{ item.user.first_name|default:'Пользователь' }}</td>
                        <td>{{ item.created_data}}</td>
                        <td>{{ item.update_data}}</td>
                        <td>{% if item.is_active %}
                                {{ item.get_status_display }}
                            {% else %}
                                удален
                            {% endif %}</td>
                        <td>
                            <a href="{% url 'admin:orders_read' item.pk %}">
                                посмотреть
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'admin:orders_update' item.pk %}">
                                редактировать
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'admin:orders_delete' item.pk %}">
                                удалить
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <a href="{% url 'main:index' %}" class="btn btn-default btn-round">
        на главную
    </a>
    <a href="{% url 'orders:create' %}" class="btn btn-default btn-round">
        новый заказ
    </a>

{% endblock %}