adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.AdminUserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.AdminUserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.AdminUserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.AdminUserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryView.as_view(), name='products_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/', adminapp.AdminOrderList.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.AdminOrderUpdate.as_view(), name='orders_update'),
    path('orders/delete/<int:pk>/', adminapp.AdminOrderDelete.as_view(), name='orders_delete'),
    path('orders/read/<int:pk>/', adminapp.AdminOrderRead.as_view(), name='orders_read'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name="index"),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('products/<int:pk>/', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models
from django.db import transaction


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    def __str__(self):
        return self.name

    @transaction.atomic()
    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)
        # self.category.delete()


class ProductQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for item in self:
            item.delete()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='category')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', db_index=True, default=True)

    objects = ProductQuerySet.as_manager()

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.select_related('category').\
            filter(is_active=True, category__is_active=True).\
            order_by('category', 'name')

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)

mainapp/views.py
from random import sample
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache

from geekshop.settings import LOW_CACHE
from mainapp.models import ProductCategory, Product


def get_links_menu():
    if LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if LOW_CACHE:
        key = 'products'
        product = cache.get(key)
        if product is None:
            product = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, product)
        return product
    return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_hot_product():
    product = get_products()
    return sample(list(product), 1)[0]


def get_same_products(hot_product):
    same_product = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_product


def main(request):
    products_list = Product.get_items()
    context = {
        'page_title': 'главная',
        'products_list': products_list
    }
    return render(request, "mainapp/index.html", context)


def products(request, pk=None, page=1):
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все',
            }
            products_list = get_products()
        else:
            category = get_category(pk)
            products_list = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                order_by('price')

        paginator = Paginator(products_list, 2)
        try:
            product_paginator = paginator.page(page)
        except PageNotAnInteger:
            product_paginator = paginator.page(1)
        except EmptyPage:
            product_paginator = paginator.page(paginator.num_pages)

        context = {
                'page_title': 'товары категории',
                'links_menu': get_links_menu(),
                'category': category,
                'products_list': product_paginator,
            }
        return render(request, "mainapp/category_products.html", context)

    hot_product = get_hot_product()
    context = {
        'page_title': 'продукты',
        'links_menu': get_links_menu(),
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, "mainapp/products.html", context)


def contact(request):
    context = {'page_title': 'контакты'}
    return render(request, "mainapp/contact.html", context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'старница продукта',
        'product': product,
        # 'categories': get_category(product.category.pk),
    }
    return render(request, 'mainapp/product_page.html', context)

mainapp/templates/includes/inc_categories_menu.html
<ul class="links-menu">
	<li>
		<a href="{% url 'main:category' 0 %}"
		class="{% if request.resolver_match.kwargs.pk == 0 %} active {% endif %}">
			все
		</a>
	</li>
	{% for link in links_menu %}
	<li>
		<a href="{% url 'main:category' link.id %}"
		class="{% if request.resolver_match.kwargs.pk == link.pk %} active {% endif %}">
			{{link.name}}
		</a>
	</li>
	{% endfor %}
</ul>

mainapp/templates/includes/inc_menu.html
 <div class="header clearfix">
    <a href='{% url "main:index" %}' class="logo"></a>
    <ul class="menu">
        <li><a href='{% url "main:index" %}'
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                домой
        </a></li>
        <li><a href='{% url "main:products" %}'
               class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">
                продукты
        </a></li>
        <li><a href='{% url "main:contact" %}'
               class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                контакты
        </a></li>

        {% if  user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        {{ user.first_name|default:'Пользователь'|title }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href='{% url "auth:edit" %}'>
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href='{% url "orders:index" %}'>
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        {% endif %}

        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:users' %}">админка</a>
            </li>
        {% endif %}

        <li>
            {% if  user.is_authenticated %}
                <a href='{% url "auth:logout" %}'>выйти</a>
            {% else %}
                <a href='{% url "auth:login" %}'>войти</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        <span>
            {% if basket %}
                {% with basket_object=basket.0.get_basket %}
                    Количество:{{ basket_object.total_quantity }}
                    Цена:{{ basket_object.total_cost }}
                {% endwith %}
            {% endif %}
        </span>
    </a>
 </div>